[book]
authors = ["Sovereign Labs <info@sovereign.xyz>"]
language = "en"
src = "src"
title = "The Sovereign SDK Book"

[output.html]
mathjax-support = true
cname = "docs.sovereign.xyz"

[output.html.playpen]
copyable = true
editable = false
runnable = false
